import type { Story } from '@/types/story';

export type ExportFormat = 'txt' | 'markdown' | 'json';

function formatStoryAsText(story: Story): string {
  const date = story.createdAt instanceof Date
    ? story.createdAt.toLocaleDateString()
    : new Date(story.createdAt).toLocaleDateString();

  return `${story.title}
${'='.repeat(story.title.length)}

Genre: ${story.parameters.genre}
Tone: ${story.parameters.tone}
Words: ${story.wordCount.toLocaleString()}
Created: ${date}

---

${story.content}

---
Generated by StoryForge AI
`;
}

function formatStoryAsMarkdown(story: Story): string {
  const date = story.createdAt instanceof Date
    ? story.createdAt.toLocaleDateString()
    : new Date(story.createdAt).toLocaleDateString();

  return `# ${story.title}

> **Genre:** ${story.parameters.genre} | **Tone:** ${story.parameters.tone} | **Words:** ${story.wordCount.toLocaleString()}
>
> *Created: ${date}*

---

${story.content}

---

*Generated by [StoryForge AI](https://story-generator-lac-nine.vercel.app)*
`;
}

function formatStoryAsJSON(story: Story): string {
  return JSON.stringify({
    title: story.title,
    content: story.content,
    metadata: {
      id: story.id,
      genre: story.parameters.genre,
      tone: story.parameters.tone,
      length: story.parameters.length,
      wordCount: story.wordCount,
      setting: story.parameters.setting,
      createdAt: story.createdAt,
    },
    generator: 'StoryForge AI',
  }, null, 2);
}

export function exportStory(story: Story, format: ExportFormat): void {
  let content: string;
  let mimeType: string;
  let extension: string;

  switch (format) {
    case 'txt':
      content = formatStoryAsText(story);
      mimeType = 'text/plain';
      extension = 'txt';
      break;
    case 'markdown':
      content = formatStoryAsMarkdown(story);
      mimeType = 'text/markdown';
      extension = 'md';
      break;
    case 'json':
      content = formatStoryAsJSON(story);
      mimeType = 'application/json';
      extension = 'json';
      break;
  }

  // Create blob and download
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);

  const link = document.createElement('a');
  link.href = url;
  link.download = `${story.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.${extension}`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  URL.revokeObjectURL(url);
}

export function getExportFormats(): { value: ExportFormat; label: string; description: string }[] {
  return [
    { value: 'txt', label: 'Plain Text', description: 'Simple text file' },
    { value: 'markdown', label: 'Markdown', description: 'Formatted for blogs/docs' },
    { value: 'json', label: 'JSON', description: 'Structured data format' },
  ];
}
